DesafioSTN.WebUI/Models/ErrorViewModel.cs
namespace DesafioSTN.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DesafioSTN.WebUI/Controllers/HomeController.cs
using DesafioSTN.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DesafioSTN.WebUI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DesafioSTN.WebUI/Controllers/PedidoController.cs
using DesafioSTN.Application.DTOs;
using DesafioSTN.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using static DesafioSTN.Helper;


namespace DesafioSTN.WebUI.Controllers
{
    public class PedidoController : Controller
    {

        private readonly IPedidoService _pedidoService;

        public PedidoController(IPedidoService pedidoService)
        {
            _pedidoService = pedidoService;
        }

        public async Task<IActionResult> IndexAsync()
        {
            return View(await _pedidoService.GetPedidos());
        }

        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(int id = 0)
        {
            if (id == 0)
                return View(new PedidoDTO());
            else
            {
                var transactionModel = await _pedidoService.GetPedidoById(id);
                if (transactionModel == null)
                {
                    return NotFound();
                }
                return View(transactionModel);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, [Bind("Id,NomeCliente,EmailCliente")] PedidoDTO pedidoDTO)
        {
            if (ModelState.IsValid)
            {
                if (id == 0)
                    await _pedidoService.Add(pedidoDTO);
                else
                {
                    try
                    {
                        PedidoUpdateDTO pedidoUpdateDTO = new PedidoUpdateDTO();
                        await _pedidoService.Update(pedidoUpdateDTO);
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!await TransactionModelExistsAsync(pedidoDTO.Id))
                        { return NotFound(); }
                        else
                        { throw; }
                    }
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", _pedidoService.GetPedidos()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "AddOrEdit", pedidoDTO) });
        }

        private async Task<bool> TransactionModelExistsAsync(int id)
        {
            var pedido = await _pedidoService.GetPedidoById(id);
            if (pedido == null)
                return false;
            return true;
        }

    }
}

DesafioSTN.WebUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DesafioSTN.WebUI/Views/Pedido/AddOrEdit.cshtml
@model DesafioSTN.Application.DTOs.PedidoDTO

@{
    Layout = null;
}

<style>
    .form-group {
        margin-bottom: 15px; /* Adiciona espaço entre as linhas */
    }

    .btn-block {
        width: 100%; /* Define a largura do botão para 100% */
    }

    .submit-button-row {
        margin-top: 15px; /* Adiciona espaço entre o valor total e o botão submit */
    }
</style>

<div class="row">
    <div class="col-md-12">
        <form asp-action="AddOrEdit" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="NomeCliente" class="control-label"></label>
                        <input asp-for="NomeCliente" class="form-control" />
                        <span asp-validation-for="NomeCliente" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label asp-for="EmailCliente" class="control-label"></label>
                        <input asp-for="EmailCliente" class="form-control" />
                        <span asp-validation-for="EmailCliente" class="text-danger"></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="ValorTotal" class="control-label"></label>
                            <input asp-for="ValorTotal" class="form-control" />
                            <span asp-validation-for="ValorTotal" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row submit-button-row"> 
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="submit" value="Submit" class="btn btn-primary btn-block" />
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

DesafioSTN.WebUI/Views/Pedido/Index.cshtml
@model IEnumerable<DesafioSTN.Application.DTOs.PedidoDTO>

@{
    ViewData["Title"] = "Index";
}


<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DesafioSTN.WebUI/Views/Pedido/_ViewAll.cshtml
@model IEnumerable<DesafioSTN.Application.DTOs.PedidoDTO>

<div class="col-md-8 offset-md-2">

    <h1 class="text-center">Pedidos</h1>


    <table class="table">
        <thead class="thead-light">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NomeCliente)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EmailCliente)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Pago)
                </th>
                <th>
                    <a onclick="showInPopup('@Url.Action("AddOrEdit","Pedido",null,Context.Request.Scheme)','Novo Pedido')" class="btn btn-success">Incluir Pedido</a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NomeCliente)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EmailCliente)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pago)
                    </td>
                    <td>
                        <div>
                            <a onclick="showInPopup('@Url.Action("AddOrEdit","Pedido",new {id=item.Id},Context.Request.Scheme)','Update Transaction')" class="btn btn-info text-white"><i class="fas fa-pencil-alt"></i> Edit</a>
                            <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                                <input type="hidden" asp-for="@item.Id" />
                                <input type="submit" value="Delete" class="btn btn-danger" />
                            </form>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

DesafioSTN.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesafioStn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesafioSTN</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pedido" asp-action="Index">Pedidos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <div class="modal" tabindex="-1" role="dialog" id="form-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
            </div>
        </div>
    </div>



    <div class="loaderbody" id="loaderbody">
        <div class="loader"></div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - jQuery_Ajax_CRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>